spring:
  application:
    name: report
  output:
    ansi:
      enabled: ALWAYS
  data:
    redis:
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
